start-at-login = true

[mode.main.binding]
alt-ctrl-cmd-slash = 'layout tiles horizontal vertical'
alt-ctrl-cmd-comma = 'layout accordion horizontal vertical'

alt-ctrl-cmd-left = 'focus left'
alt-ctrl-cmd-down = 'focus down'
alt-ctrl-cmd-up = 'focus up'
alt-ctrl-cmd-right = 'focus right'

alt-ctrl-cmd-shift-minus = 'resize smart -50'
alt-ctrl-cmd-shift-equal = 'resize smart +50'

alt-ctrl-cmd-a = 'workspace A'
alt-ctrl-cmd-b = 'workspace B'
alt-ctrl-cmd-c = 'workspace C'
alt-ctrl-cmd-d = 'workspace D'
alt-ctrl-cmd-e = 'workspace E'
alt-ctrl-cmd-f = 'workspace F'
alt-ctrl-cmd-g = 'workspace G'
alt-ctrl-cmd-h = 'workspace H'
alt-ctrl-cmd-i = 'workspace I'
alt-ctrl-cmd-j = 'workspace J'
alt-ctrl-cmd-k = 'workspace K'
alt-ctrl-cmd-l = 'workspace L'
alt-ctrl-cmd-m = 'workspace M'
alt-ctrl-cmd-n = 'workspace N'
alt-ctrl-cmd-o = 'workspace O'
alt-ctrl-cmd-p = 'workspace P'
alt-ctrl-cmd-q = 'workspace Q'
alt-ctrl-cmd-r = 'workspace R'
alt-ctrl-cmd-s = 'workspace S'
alt-ctrl-cmd-t = 'workspace T'
alt-ctrl-cmd-u = 'workspace U'
alt-ctrl-cmd-v = 'workspace V'
alt-ctrl-cmd-w = 'workspace W'
alt-ctrl-cmd-x = 'workspace X'
alt-ctrl-cmd-y = 'workspace Y'
alt-ctrl-cmd-z = 'workspace Z'
alt-ctrl-cmd-esc = []

alt-ctrl-cmd-shift-a = 'move-node-to-workspace A'
alt-ctrl-cmd-shift-b = 'move-node-to-workspace B'
alt-ctrl-cmd-shift-c = 'move-node-to-workspace C'
alt-ctrl-cmd-shift-d = 'move-node-to-workspace D'
alt-ctrl-cmd-shift-e = 'move-node-to-workspace E'
alt-ctrl-cmd-shift-f = 'move-node-to-workspace F'
alt-ctrl-cmd-shift-g = 'move-node-to-workspace G'
alt-ctrl-cmd-shift-h = 'move-node-to-workspace H'
alt-ctrl-cmd-shift-i = 'move-node-to-workspace I'
alt-ctrl-cmd-shift-j = 'move-node-to-workspace J'
alt-ctrl-cmd-shift-k = 'move-node-to-workspace K'
alt-ctrl-cmd-shift-l = 'move-node-to-workspace L'
alt-ctrl-cmd-shift-m = 'move-node-to-workspace M'
alt-ctrl-cmd-shift-n = 'move-node-to-workspace N'
alt-ctrl-cmd-shift-o = 'move-node-to-workspace O'
alt-ctrl-cmd-shift-p = 'move-node-to-workspace P'
alt-ctrl-cmd-shift-q = 'move-node-to-workspace Q'
alt-ctrl-cmd-shift-r = 'move-node-to-workspace R'
alt-ctrl-cmd-shift-s = 'move-node-to-workspace S'
alt-ctrl-cmd-shift-t = 'move-node-to-workspace T'
alt-ctrl-cmd-shift-u = 'move-node-to-workspace U'
alt-ctrl-cmd-shift-v = 'move-node-to-workspace V'
alt-ctrl-cmd-shift-w = 'move-node-to-workspace W'
alt-ctrl-cmd-shift-x = 'move-node-to-workspace X'
alt-ctrl-cmd-shift-y = 'move-node-to-workspace Y'
alt-ctrl-cmd-shift-z = 'move-node-to-workspace Z'

alt-ctrl-cmd-tab = 'workspace-back-and-forth'
alt-ctrl-cmd-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-ctrl-cmd-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']

alt-ctrl-cmd-left = ['move left', 'mode main']
alt-ctrl-cmd-down = ['move down', 'mode main']
alt-ctrl-cmd-up = ['move up', 'mode main']
alt-ctrl-cmd-right = ['move right', 'mode main']

alt-ctrl-cmd-shift-left = ['join-with left', 'mode main']
alt-ctrl-cmd-shift-down = ['join-with down', 'mode main']
alt-ctrl-cmd-shift-up = ['join-with up', 'mode main']
alt-ctrl-cmd-shift-right = ['join-with right', 'mode main']
